Shannon!
sean-rohan-NOAA/trawlmetrics pull request #8
Opened 2024-02-28 21:21 UTC by ShannonNardi-NOAA

start of modeling code and updated combined script

2024-02-29 00:33 UTC, sean-rohan-NOAA requested changes

2024-02-29 00:33 UTC, sean-rohan-NOAA commented on R/get_model.R
This one still need to be converted to a function before I can merge the change. With the current setup, the package won't build correctly since the code isn't in a function.

2024-02-29 14:58 UTC, ShannonNardi-NOAA commented
Right! Duh! Ok I'll work on that today and commit it again when it's fixed!


On Wed, Feb 28, 2024 at 4:34 PM Sean Rohan ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On R/get_model.R
> <https://github.com/sean-rohan-NOAA/trawlmetrics/pull/8#discussion_r1506837332>
> :
>
> This one still need to be converted to a function before I can merge the
> change. With the current setup, the package won't build correctly since the
> code isn't in a function.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sean-rohan-NOAA/trawlmetrics/pull/8#pullrequestreview-1907703551>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFTTP6WII6EILKKQXOCBEJTYV7EHHAVCNFSM6AAAAABD6Y5KACVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBXG4YDGNJVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-05 17:49 UTC, sean-rohan-NOAA commented on R/get_model.R
This works for now, but we'll need to clean up the code later (e.g. removing head(), which doesn't do anything within the context of this function).

2024-03-05 17:50 UTC, sean-rohan-NOAA approved these changes

2024-03-05 17:50 UTC, merged